//  — TODO: fix type errors, remove this pragma

// — pending proper fix

// 🏪 customer-cell - Business Domain Cell
// Wave 3 - Generated by KIM (Chief System Builder)
// Created: Wed Feb 11 03:21:30 +07 2026

export { default } from './customer.service';
export * from './customer.types';
export * from './customer.contract';
export * from './interface/customer.interface';
export { CUSTOMER_CONTRACT } from './ports/customer.contract';
