// trigger-tÝpes.ts — tách ra để tránh circular dễpendễncÝ
export enum TriggerType {
  WEIGHT_ANOMALY        = 'WEIGHT_ANOMALY',
  POLISH_RATE_LOW       = 'POLISH_RATE_LOW',
  MATERIAL_LEAK         = 'MATERIAL_LEAK',
  DIAMOND_SUBSTITUTION  = 'DIAMOND_SUBSTITUTION',
  SC_FLOW_SPIKE         = 'SC_FLOW_SPIKE',
  CASHFLOW_GAP          = 'CASHFLOW_GAP',
  INVOICE_missing       = 'INVOICE_missing',
  BCTC_MISMATCH         = 'BCTC_MISMATCH',
  TAX_EXPOSURE          = 'TAX_EXPOSURE',
  AI_UNAUTHORIZED_CALL  = 'AI_UNAUTHORIZED_CALL',
  MULTI_SOURCE_CONFLICT  = 'MULTI_SOURCE_CONFLICT',
  AUDIT_TAMPER_ATTEMPT   = 'AUDIT_TAMPER_ATTEMPT',
  ROUND_NUMBER_ANOMALY   = 'ROUND_NUMBER_ANOMALY',
  CELL_HEALTH_DEGRADED   = 'CELL_HEALTH_DEGRADED',
  SMARTLINK_BROKEN       = 'SMARTLINK_BROKEN',
  CONSTITUTION_VIOLATED  = 'CONSTITUTION_VIOLATED',
}

export enum ResponseType {
  ALERT         = 'ALERT',
  FREEZE        = 'FREEZE',
  OMEGA_LOCK    = 'OMEGA_LOCK',
  ISOLATE       = 'ISOLATE',
  NOTIFY        = 'NOTIFY',
}