#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
scan_report_generator.py
========================
@nauion-tool python-pure v1
@scope sovereign-audit-report-generator
@paradigm B (Bash thuần — anh hai Thiên Lớn ratify ss20260427)
@invoked-by nattos.sh §39 REPORT GENERATOR
@authority Sirawat Băng (Obikeeper QNEU 313.5)

Generate audit report by aggregating twin + arch JSON files.
Output:
  - audit/summary/latest.json (always)
  - audit/reports/<ts>_auto.md (only when issues detected)
  - audit/log cleanup (keep 90 most recent)
"""
import os
import sys
import json
from datetime import datetime
from pathlib import Path


def main() -> int:
    os.makedirs("audit/summary", exist_ok=True)
    os.makedirs("audit/reports", exist_ok=True)
    os.makedirs("audit/log", exist_ok=True)

    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    date_str = datetime.now().strftime("%Y-%m-%d")
    ts_file = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    twin_path = Path(".nattos-twin/inference.json")
    twin = {}
    if twin_path.exists():
        try:
            twin = json.loads(twin_path.read_text())
        except Exception:
            pass

    arch_path = Path(".nattos-twin/arch-map.json")
    arch = {}
    if arch_path.exists():
        try:
            arch = json.loads(arch_path.read_text())
        except Exception:
            pass

    latest = {
        "ts": ts,
        "state": twin.get("state", "UNKNOWN"),
        "risk": twin.get("risk", -1),
        "issues": twin.get("issues", []) + arch.get("issues", []),
        "hostname": arch.get("hostname", "unknown")
    }
    with open("audit/summary/latest.json", "w") as f:
        json.dump(latest, f, indent=2)
    print(f"  \033[0;32m✅\033[0m latest.json updated: {ts}")

    all_issues = latest["issues"]
    if all_issues:
        report_path = f"audit/reports/{ts_file}_auto.md"
        lines = [
            f"# natt-os Audit Report — {date_str}",
            f"",
            f"**Generated:** {ts}  ",
            f"**System State:** {latest['state']}  ",
            f"**Risk:** {latest['risk']}/100  ",
            f"**Machine:** {latest['hostname']}  ",
            f"",
            f"## Issues Detected ({len(all_issues)})",
            f"",
        ]
        for issue in all_issues:
            lines.append(f"- {issue}")
        lines += [
            f"",
            f"## Gatekeeper Sign-off",
            f"",
            f"- [ ] Reviewed by Gatekeeper: _______________",
            f"- [ ] Date: _______________",
            f"- [ ] Signature: Nattsira Governance Seal",
            f"",
            f"---",
            f"*Auto-generated by SmartAudit v5.3 — NOT official until signed*"
        ]
        with open(report_path, "w") as f:
            f.write("\n".join(lines))
        print(f"  \033[0;33m⚠️\033[0m  Report generated: {report_path}")
        print(f"  \033[0;36mℹ\033[0m  Sign and commit to make official")
    else:
        print(f"  \033[0;32m✅\033[0m No issues — report not needed")

    log_files = sorted(Path("audit/log").glob("*.log"))
    if len(log_files) > 90:
        for old in log_files[:-90]:
            old.unlink()
        print(f"  \033[0;36mℹ\033[0m  Cleaned old logs, kept 90")

    return 0


if __name__ == "__main__":
    sys.exit(main())
